"""add_account_id_to_export_history

Revision ID: 7bf5d11a9da8
Revises: e69e0119d609
Create Date: 2026-06-03 08:49:48.690192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf5d11a9da8'
down_revision: Union[str, None] = 'e69e0119d609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('export_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_export_history_account_id'), ['account_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_export_history_account_id_credentials',
            'credentials',
            ['account_id'],
            ['id'],
            ondelete='SET NULL',
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('export_history', schema=None) as batch_op:
        batch_op.drop_constraint('fk_export_history_account_id_credentials', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_export_history_account_id'))
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###
